apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: HEAP_NEWSIZE
              value: 100M
            - name: MAX_HEAP_SIZE
              value: 512M
          image: cassandra:3
          name: cassandra
          ports:
            - containerPort: 9042
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: cassandra-claim
      volumes:
        - name: cassandra-claim
          persistentVolumeClaim:
            claimName: cassandra-claim
