apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seq
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
          image: datalust/seq:latest
          name: seq
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: seq-claim
      volumes:
        - name: seq-claim
          persistentVolumeClaim:
            claimName: seq-claim