apiVersion: apps/v1
kind: Deployment
metadata:
  name: versiontwo
  labels:
    app: versiontwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: versiontwo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: versiontwo
    spec:
      restartPolicy: Always
      containers:
        - image: versiontwo:local
          name: versiontwo-app
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: versiontwo-config
          volumeMounts:
            - mountPath: /var/www
              name: versiontwo-www
          workingDir: /var/www/
          resources:
            limits:
              cpu: 0.5 #limits the CPU per pod to half a cpu-core.
            requests:
              cpu: 0.3
      volumes:
        - name: versiontwo-www
          persistentVolumeClaim:
            claimName: versiontwo-www-pvc
