apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  ports:
    - name: main
      port: 80
      targetPort: 9411
    - name: extra
      port: 9411
      targetPort: 9411
  selector:
    app: zipkin
