apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: seq
