apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipments-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: shipments
