apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: versiontwo-www-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: versiontwo
